# Generated by Django 2.2.16 on 2022-03-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220308_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='Category',
            new_name='category',
        ),
    ]
