# Generated by Django 2.2.16 on 2022-03-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220308_2035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviews',
            name='uniq',
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='uniq'),
        ),
    ]
